[features]
seeds = false
skip-lint = false

[programs.devnet]
solana_nft_anchor = "ungaE9gfvL1r3eUWqn1nki684J36n2QVtTwrHMvDcdL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/dev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
